defaults:
  - view_sampler: bounded

name: re10k_unposed
roots: [datasets/re10k]
make_baseline_1: false
augment: false
image_shape: [256, 256]
da3_image_shape: [336, 336]
da3_process_res: 336
da3_process_res_method: upper_bound_resize
da3_model: depth-anything/DA3-SMALL
da3_device: cuda
da3_ref_view_strategy: middle
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false
baseline_epsilon: 1e-3
max_fov: 100.0
skip_bad_shape: false
near: -1.0
far: -1.0
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
train_times_per_scene: 1
test_times_per_scene: 1
use_index_to_load_chunk: false
